export const preload =
    [
        {
            name: "Default",
            minDecibels: -100,
            maxDecibels: -30,
            highMinHz: 6000, 
            highMaxHz: 20000,
            highPeak: 150,
            midMinHz: 500,
            midMaxHz: 2000,
            midPeak: 180,
            lowMinHz: 250,
            lowMaxHz: 500,
            lowPeak: 180,
            bassMinHz: 60,
            bassMaxHz: 250,
            bassPeak: 180,
            boomMinHz: 0,
            boomMaxHz: 2000,
            boomPeak: 255
        },
        {
            name: "AC/DC - Thunderstruck",
            minDecibels: -100,
            maxDecibels: -30,
            highMinHz: 930, 
            highMaxHz: 1400,
            highPeak: 200,
            midMinHz: 366,
            midMaxHz: 580,
            midPeak: 210,
            lowMinHz: 280,
            lowMaxHz: 486,
            lowPeak: 173,
            bassMinHz: 21,
            bassMaxHz: 107,
            bassPeak: 243,
            boomMinHz: 0,
            boomMaxHz: 2000,
            boomPeak: 255
    },
    {
        "minDecibels": "-100",
        "maxDecibels": "-30",
        "highMinHz": "0",
        "highMaxHz": "0",
        "highPeak": "0",
        "midMinHz": "0",
        "midMaxHz": "0",
        "midPeak": "0",
        "lowMinHz": "0",
        "lowMaxHz": "0",
        "lowPeak": "0",
        "bassMinHz": "0",
        "bassMaxHz": "0",
        "bassPeak": "0",
        "boomMinHz": "0",
        "boomMaxHz": "0",
        "boomPeak": "0",
        "name": "Off"
      },
      {
        "minDecibels": -100,
        "maxDecibels": "-13",
        "highMinHz": 6000,
        "highMaxHz": 20000,
        "highPeak": "135",
        "midMinHz": 500,
        "midMaxHz": 2000,
        "midPeak": "189",
        "lowMinHz": 250,
        "lowMaxHz": 500,
        "lowPeak": "192",
        "bassMinHz": 60,
        "bassMaxHz": 250,
        "bassPeak": "217",
        "boomMinHz": 0,
        "boomMaxHz": 2000,
        "boomPeak": "235",
        "name": "Dragonforce"
      }
]